[package]
name = "marketplace"
version = "0.1.0"
authors = ["dariofs.near","stolkerve.near"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
rand = "0.8.0"
getrandom = { version = "0.2", features = ["js"] }
# near-env = "0.1.10"
