[package]
name = "marketplace"
version = "0.1.0"
authors = ["dariofs.near","stolkerve.near"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
serde = "1"
serde_json = "1"
serde_with = "1"
# near-env = "0.1.10"
