[package]
name = "ft"
version = "0.1.0"
authors = ["dariofs.near", "stolkerve.near"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-contract-standards = "3.2.0"
near-sdk = "3.1.0"