[package]
name = "ft"
version = "1.0.0"
authors = ["dariofs.near", "stolkerve.near"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "3.2.0"
near-sdk = "3.1.0"